
name: Run GoodBoy Report Daily

on:
  schedule:
    - cron: '0 0 * * *'  # 매일 오전 9시 KST (24시 UTC)
  workflow_dispatch:

jobs:
  run-notebook:
    runs-on: ubuntu-latest
    steps:
      - name: Install Jupyter and kernel
        run: |
         pip install jupyter ipykernel nbconvert
         python -m ipykernel install --user --name python3
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install torch
          pip install -r requirements.txt
          pip install requests transformers nbformat nbconvert
      - name: Run script
        env:
          NAVER_CLIENT_ID : ${{secrets.NAVER_CLIENT_ID}}
          NAVER_CLIENT_SECRET : ${{secrets.NAVER_CLIENT_SECRET}}
          NOTION_API_TOKEN :  ${{secrets.NOTION_API_TOKEN}}
          DATABASE_ID :  ${{secrets.DATABASE_ID}}
        run: python main.py
